version: '3.8'

services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: ["node", "server.js"]